# ML-04 — Search Intelligence Data Contract

This skeleton is yours to fill. Work the sections **in order** — each one has a one-line hint. Simple words, honest numbers.

> Working with an AI assistant? Tell it to read `skills/README.md` first and load the one skill this assignment names on its card.

## 1. Unit of analysis + time window

*One row = one what, over which dates? State it, then verify it below.*

In [10]:
#read data from hugging face
from google.colab import userdata
from datasets import load_dataset

hf_token = userdata.get('HF_token')
dataset_content = load_dataset("FlyRank/internship-warehouse", 'dim_content', token=hf_token)

In [2]:
import duckdb
from google.colab import userdata

con = duckdb.connect()

# Retrieve HF_token from user data
hf_token = userdata.get('HF_token')

# Replace with your HF read token
con.execute(f"""
CREATE SECRET (
    TYPE huggingface,
    TOKEN '{hf_token}'
)
""")

#### Get column names for `fact_content_daily_performance` using DuckDB (without loading full data)

We can use DuckDB's `PRAGMA table_info` command to inspect the schema of the parquet files directly, which provides column names and their data types without needing to load the entire dataset into memory.

In [13]:

import pandas as pd
from datasets import load_dataset # Added this import

print("\n--- Column names and types for fact_content_daily_performance (via small sample) ---")

# Load the full fact_content_daily_performance dataset using the datasets library
# (This just loads metadata and prepares for streaming, not the full data into memory)
print("Loading 'fact_content_daily_performance' dataset metadata...")
dataset_performance_hf = load_dataset("FlyRank/internship-warehouse", 'fact_content_daily_performance', token=hf_token)

# Select a small sample (e.g., first 10 rows) from the 'train' split
# This minimizes memory usage while providing enough data to infer schema
print("Converting a small sample (e.g., first 10 rows) to pandas DataFrame...")
df_performance_sample = dataset_performance_hf['train'].select(range(10)).to_pandas()

# Create a temporary DuckDB view from this small sample DataFrame
con.from_df(df_performance_sample).create_view('temp_performance_schema') # Corrected method

# Use PRAGMA table_info on the temporary view to get the schema
duckdb_columns = con.execute("PRAGMA table_info('temp_performance_schema');").df()

# Extract just the column names
print("\nColumn Names:")
print(duckdb_columns['name'].tolist())

print("\nColumn Info (Name, DuckDB Type):")
display(duckdb_columns[['name', 'type']])

# Clean up the temporary view
con.execute("DROP VIEW temp_performance_schema;")

--- Column names and types for fact_content_daily_performance (via small sample) ---
Loading 'fact_content_daily_performance' dataset metadata...

Resolving data files:   0%|          | 0/18 [00:00<?, ?it/s]

Downloading data:   0%|          | 0/18 [00:00<?, ?files/s]

fact_content_daily_performance/month=202(…): reconstructing file:   0%|          |  0.00B / 19.6kB

fact_content_daily_performance/month=202(…): downloading bytes:           |  0.00B

fact_content_daily_performance/month=202(…): reconstructing file:   0%|          |  0.00B / 1.45MB

fact_content_daily_performance/month=202(…): reconstructing file:   0%|          |  0.00B / 8.93MB

fact_content_daily_performance/month=202(…): reconstructing file:   0%|          |  0.00B /  624kB

fact_content_daily_performance/month=202(…): reconstructing file:   0%|          |  0.00B / 89.0MB

fact_content_daily_performance/month=202(…): reconstructing file:   0%|          |  0.00B / 4.41MB

fact_content_daily_performance/month=202(…): reconstructing file:   0%|          |  0.00B /  134MB

fact_content_daily_performance/month=202(…): reconstructing file:   0%|          |  0.00B / 7.12MB

fact_content_daily_performance/month=202(…): reconstructing file:   0%|          |  0.00B / 3.22MB

fact_content_daily_performance/month=202(…): reconstructing file:   0%|          |  0.00B / 21.6MB

fact_content_daily_performance/month=202(…): downloading bytes:           |  0.00B

fact_content_daily_performance/month=202(…): downloading bytes:           |  0.00B

fact_content_daily_performance/month=202(…): downloading bytes:           |  0.00B

fact_content_daily_performance/month=202(…): reconstructing file:   0%|          |  0.00B / 86.2MB

fact_content_daily_performance/month=202(…): reconstructing file:   0%|          |  0.00B / 90.3MB

fact_content_daily_performance/month=202(…): reconstructing file:   0%|          |  0.00B / 72.0MB

fact_content_daily_performance/month=202(…): downloading bytes:           |  0.00B

fact_content_daily_performance/month=202(…): downloading bytes:           |  0.00B

fact_content_daily_performance/month=202(…): downloading bytes:           |  0.00B

fact_content_daily_performance/month=202(…): downloading bytes:           |  0.00B

fact_content_daily_performance/month=202(…): reconstructing file:   0%|          |  0.00B / 2.62MB

fact_content_daily_performance/month=202(…): downloading bytes:           |  0.00B

fact_content_daily_performance/month=202(…): reconstructing file:   0%|          |  0.00B /  124MB

fact_content_daily_performance/month=202(…): reconstructing file:   0%|          |  0.00B / 3.29MB

fact_content_daily_performance/month=202(…): downloading bytes:           |  0.00B

fact_content_daily_performance/month=202(…): downloading bytes:           |  0.00B

fact_content_daily_performance/month=202(…): downloading bytes:           |  0.00B

fact_content_daily_performance/month=202(…): downloading bytes:           |  0.00B

fact_content_daily_performance/month=202(…): downloading bytes:           |  0.00B

fact_content_daily_performance/month=202(…): downloading bytes:           |  0.00B

fact_content_daily_performance/month=202(…): downloading bytes:           |  0.00B

fact_content_daily_performance/month=202(…): reconstructing file:   0%|          |  0.00B /  149MB

fact_content_daily_performance/month=202(…): downloading bytes:           |  0.00B

fact_content_daily_performance/month=202(…): reconstructing file:   0%|          |  0.00B /  146MB

fact_content_daily_performance/month=202(…): downloading bytes:           |  0.00B

Generating train split:   0%|          | 0/78835655 [00:00<?, ? examples/s]

Loading dataset shards:   0%|          | 0/39 [00:00<?, ?it/s]

Converting a small sample (e.g., first 10 rows) to pandas DataFrame...

Column Names:
['report_date', 'client_hash_id', 'content_hash_id', 'client_has_gsc', 'client_has_ga4', 'gsc_data_available', 'ga4_data_available', 'gsc_impressions', 'gsc_clicks', 'gsc_sum_position', 'gsc_avg_position', 'ga4_pageviews', 'ga4_sessions', 'ga4_users', 'ga4_engaged_sessions', 'ga4_total_engagement_sec', 'sessions_organic', 'sessions_direct', 'sessions_referral', 'sessions_social', 'sessions_paid', 'sessions_ai', 'ai_chatgpt', 'ai_perplexity', 'ai_gemini', 'ai_copilot', 'ai_claude', 'ai_meta', 'ai_other', 'scroll_events']

Column Info (Name, DuckDB Type):

                        name     type
0                report_date     DATE
1             client_hash_id  VARCHAR
2            content_hash_id  VARCHAR
3             client_has_gsc  BOOLEAN
4             client_has_ga4  BOOLEAN
5         gsc_data_available  BOOLEAN
6         ga4_data_available  BOOLEAN
7            gsc_impressions   BIGINT
8                 gsc_clicks   BIGINT
9           gsc_sum_position   BIGINT
10          gsc_avg_position   DOUBLE
11             ga4_pageviews   BIGINT
12              ga4_sessions   BIGINT
13                 ga4_users   BIGINT
14      ga4_engaged_sessions   BIGINT
15  ga4_total_engagement_sec   BIGINT
16          sessions_organic   BIGINT
17           sessions_direct   BIGINT
18         sessions_referral   BIGINT
19           sessions_social   BIGINT
20             sessions_paid   BIGINT
21               sessions_ai   BIGINT
22                ai_chatgpt   BIGINT
23             ai_perplexity   BIGINT
24                 ai_gemini   BIGINT
25                ai_copilot   BIGINT
26                 ai_claude   BIGINT
27                   ai_meta   BIGINT
28                  ai_other   BIGINT
29             scroll_events   BIGINT

In [3]:
df_performance = con.sql("""
SELECT
    content_hash_id,
    client_hash_id,
    report_date,
    gsc_avg_position,
    gsc_data_available,
    gsc_impressions,
    gsc_clicks,
    ga4_pageviews,
    sessions_organic,
    client_has_gsc
FROM read_parquet(
    'hf://datasets/FlyRank/internship-warehouse/fact_content_daily_performance/month=2026-03/*.parquet'
)
""").df()

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

In [11]:
df_performance.head()

,content_hash_id,client_hash_id,report_date,gsc_avg_position,gsc_data_available,gsc_impressions,gsc_clicks,ga4_pageviews,sessions_organic,client_has_gsc
0,content_b7e512995f79d5a6,client_73cda7b4e4f265ea,2026-03-01,3.350000,True,20,0,<NA>,<NA>,True
1,content_05597932fe4da067,client_73cda7b4e4f265ea,2026-03-01,0.000000,True,1,0,<NA>,<NA>,True
2,content_7a105f548d9c6916,client_73cda7b4e4f265ea,2026-03-01,4.928000,True,125,1,<NA>,<NA>,True
3,content_905aa32a0230694e,client_73cda7b4e4f265ea,2026-03-01,4.000000,True,7,0,<NA>,<NA>,True
4,content_a3ea9792f793ec72,client_73cda7b4e4f265ea,2026-03-01,2.272727,True,11,0,<NA>,<NA>,True

 unit of analysis is a 'content_hash_id'.
 time window is 2026-03

## 2. Fields: feature / label / context / excluded

*Sort every field you plan to touch into these four buckets. Excluded needs a why.*

| Category     | Example Columns                                                                                                                                     |
| ------------ | --------------------------------------------------------------------------------------------------------------------------------------------------- |
| **Label**    | `avg_position`                                                                                                                                      |
| **Features** | impressions, clicks, CTR, search_volume, competition, keyword_length, backlinks_count, page_speed, freshness_days, content_length, device, language |
| **Context**  | date, month, country, domain, page_type, search_engine                                                                                              |
| **Excluded** | keyword_id, URL, row_id, rank, position, visibility_score, future metrics                                                                           |

| Leaky Feature    | Reason                               |
| ---------------- | ------------------------------------ |
| Impressions      | Result of ranking                    |
| Clicks           | Result of ranking                    |
| Sessions         | Result of ranking                    |
| Users            | Result of ranking                    |
| CTR              | Depends on ranking and impressions   |
| Engagement Rate  | Behaviour after users arrive         |
| Scroll Rate      | Behaviour after users arrive         |
| AI Sessions      | Traffic outcome                      |
| Trend Direction  | Derived from performance             |
| Trend Percentage | Derived from performance             |
| Position Tier    | Directly derived from `avg_position` |

## 3. Verify it with queries (grain, counts, missing values, windows)

*Every claim above gets a query cell here. A contract claim without a query next to it is a guess.*

## 4. Data limits

*What can this data never tell you? Unbalanced history, GSC-only early rows, window overlaps.*

## Self-check

Before you submit, confirm each line honestly:

- [ ] Every section above is filled — markdown thinking AND the code that backs it
- [ ] The notebook runs top to bottom with no errors (Runtime → Run all)
- [ ] No client names, URLs, or private queries anywhere
- [ ] My claims use careful words: observed, measured, directional, decision-support
- [ ] Committed to my repo under `work/notebooks/` — then submit your repo URL on the card. Done.